### ISSUE TITLE
server: support Arkimet BUFR in Borinud

### ISSUE THREAD

**Issue by edigiacomo** [r-map/rmap#106]
Support Arkimet BUFR in Borinud.

**Comment by edigiacomo** [comment]
@pat1 is this issue part of the Milestone *server rmap release 2*?

**Comment by pat1** [comment]
si mettiamola !

**Comment by edigiacomo** [comment]
Ho iniziato il lavoro in f7d7d76 ma c'è ancora un po' da fare:
- L'elenco delle terne `var`, `level`, `trange` è predefinito per tutto il dataset: è come se tutte le stazioni misurassero sempre le stesse variabili (una sorta di template). Mi rendo conto che è una grossa approssimazione, ma sarebbe già qualcosa.
- La query delle stazioni non restituisce nessun dato statico: è come se le stazioni non ne avessero, si deve capire come tenere traccia di dati statici di stazione.
- Da integrare nella configurazione `BORINUD["SOURCES"]`: una volta che è possibile specificare questo tipo di database da `settings.py`, direi di testarne il funzionamento, chiudere questa issue e crearne due (una per ognuno dei due punti precedenti), così possiamo discutere come muoverci e fin dove arrivare per completare la milestone.
