### ISSUE TITLE
server: Borinud ArkimetBufrDB deve sapere cosa misura ogni stazione

### ISSUE THREAD

**Issue by edigiacomo** [r-map/rmap#110]
Attualmente [`ArkimetBufrDB.query_summary`](https://github.com/r-map/rmap/blob/29df9ba990c4d3f25da9d8e1b4862105c5636fac/python/borinud/utils/source.py#L397-L428) fornisce un summary in cui l'elenco delle misurazioni di una stazione è prefissato.

Per poter sapere cosa misura ogni stazione e, per ogni misurazione, in quale periodo di tempo, si dovrebbero leggere tutti i `BUFR` archiviati.

**Comment by pat1** [comment]
solved using the explorer
