### ISSUE TITLE
server: bufr2mqtt freeze

### ISSUE THREAD

**Issue by pat1** [r-map/rmap#119]
mqtt2bufr freeze 
try with apache restart

**Comment by edigiacomo** [comment]
Scusa, ma non capisco la issue. Cosa c'entra mqtt2bufr con Apache? E in che modo si "congela"?

**Comment by pat1** [comment]
scusa, ho sbagliato tutto, era più che altro una nota per non perdermelo.
bufr2mqtt
il freeze è possibile che avvenga quando si ferma apache.
Apache fornisce il servizio http per l'autenticazione di mosquitto.
E' possibile che questo generi un errore e faccia andare in loop infinito bufr2mqtt.

**Comment by edigiacomo** [comment]
Nessun problema, mi mancava il pezzo dell'autenticazione via Apache per Mosquitto.

Ci guardiamo a quattro occhi, allora, non appena ci incrociamo al lavoro.

**Comment by pat1** [comment]
closed by d8ccb20
