### ISSUE TITLE
server: borinud do not show menu to select parameter, timerange ....

### ISSUE THREAD

**Issue by pat1** [r-map/rmap#130]
http://rmap.cc/borinud/

**Comment by edigiacomo** [comment]
An `URLError` (`connection refused`) is raised during the Arkimet summary request (see stacktrace in http://rmap.cc/borinud/api/v1/*/*/*/*/*/*/summaries). Without the summary, the JavaScript code cannot build the menu.

Please check the Arkimet server.

**Comment by pat1** [comment]
Attivato servizio arkimet al boot. Così al prossimo riavvio non avremo questo problema.
