### ISSUE TITLE
AT+CIPSTART to should handle case for ALREADY CONNECTED

### ISSUE THREAD

**Issue by dmsherazi** [r-map/rmap#158]
If we have an existing connection and try AT+CIPSTART the reply would be 

```
ERROR
ALREADY CONNECTED
``` 

This case is currently not handled

**Comment by pat1** [comment]
Can you show an example with call to library?
AT+CIPSTART is inside
bool SIM800::TCPconnect(const char* server, int port)
that set STATE_HTTPINITIALIZED in state and this state is checked by SIM800::isHttpInitialized() and returned by sim800Client::connected()

OK, no comment on variable names derived by patch applied in time ...
but you can call connected() before a new connect.

**Comment by pat1** [comment]
without other information I will close this ...

**Comment by pat1** [comment]
no information on this bug
