### ISSUE TITLE
stima firmware: mqtt do not manage qos 1 in publish

### ISSUE THREAD

**Issue by pat1** [r-map/rmap#160]
https://github.com/knolleary/pubsubclient/pull/100

**Comment by pat1** [comment]
duplicated #31

**Comment by lahirue** [comment]
What is the meaning of this topic ? Why MTT not manage QOS 1 in Publish ? Is it only for this client ?

https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/
