### ISSUE TITLE
firmware: BMP driver  with  sensordriver library return temperature with value 0

### ISSUE THREAD

**Issue by pat1** [r-map/rmap#171]
use getdata.in in sensordriver example:
BMP : {"B10004":100650,"B12101":0}

**Comment by pat1** [comment]
@dcast78 mi potresti dire la sigla del BMP per vedere se corrisponde al mio?

**Comment by pat1** [comment]
la temperatura del bpm viene letta "raw" e non restituita dal driver. Il commit  f8d925e rimuove la falsa temperatura 0 e riporta solo la pressione.
Modificato da bug a miglioramento.

**Comment by dcast78** [comment]
Shield sensore di pressione barometrica BMP085 arduino pic ART. CF06

http://ebmstore.it/index.php?route=product/product&product_id=1380

Il 08 ott 2016 3:03 PM, "Paolo Patruno" <notifications@github.com> ha
scritto:

**Comment by pat1** [comment]
closed by d2e5a84e835e7887084bf4cefe452aaf57e85a89
