### ISSUE TITLE
Specs for Borinud API

### ISSUE THREAD

**Issue by edigiacomo** [r-map/rmap#193]
Replace #181

**Comment by pat1** [comment]
ora sono implementati
summaries
spatialseries
timeseries
stations

c'è una infrastruttura per stationdata non funzionante

**Comment by edigiacomo** [comment]
Ok. Teniamo traccia dei servizi e dei formati in modo da aggiornare http://www.raspibo.org/wiki/index.php/Gruppo_Meteo/RFC-rmap#RMAP_web_services.
