### ISSUE TITLE
Arduino interface with Sim800 using MQTT protocol

### ISSUE THREAD

**Issue by priya2212** [r-map/rmap#218]
Hello everyone,
I am using this example `https://github.com/r-map/rmap/tree/master/arduino/sketchbook/libraries/sim800/examples/mqtt_basic` to run MQTT over Sim800 module. I am using Arduino UNO to interface with SIm800 module. So, to disable the serial1 port, I comment out this line on sim800.h:

> //#define DEBUGONSERIAL
> #define ENABLEWDT 1
> // if define HARDWARESERIAL is set then it will be static (required by Time library)
> **//#define HARDWARESERIAL Serial1**

But it is giving me error in my main file:
error: 'Serial1' was not declared in this scope
     if (s800.init(&Serial1 , 7, 6)) break;
My understanding for this is :As I am disabling the hardware serial, due to this it is not able to find serial1, so giving me this error. 

I used software serial library in my main program and created an instance for using software serial;
> #include <SoftwareSerial.h>
> SoftwareSerial myserial(7,6);
> & change the code to use myserial as:
> if (s800.init(&myserial, 7, 6)) break;

But, It is throwing me error:
error: no matching function for call to 'sim800Client::init(SoftwareSerial*, int, int)'
     if (s800.init(&myserial, 7, 6)) break;

I want to use software serial for my UNO, It would be great for me if anyone can guide me for how to use software serial with this library because whenever I am disabling the hardware serial, it is throwing a lot of errors in the library. 
Please help me!
Thanks & Regards,
Priya

**Comment by pat1** [comment]
Take a look here:
https://github.com/r-map/rmap/issues/202

also you have to change in 
https://github.com/r-map/rmap/blob/master/arduino/sketchbook/libraries/PubSubClient/PubSubClient.h
uncomment:
#include "sim800Client.h"
#define TCPCLIENT sim800Client

and commet:
//#include "Client.h"
//#include "Stream.h"
//#define TCPCLIENT Client

**Comment by priya2212** [comment]
Hi @pat1, Thank you so much for your response. I have uncommented and commented the above required stuff. It is still throwing me the error. & And I have gone through the issue #202 for using serial of Arduino UNO. but I'm not getting any response at the end of other client when I'm subscribing to the topic. Even the module is not initiating connection with TCP/IP as well and I am not able to debug it as I have disabled the serial.

**Comment by pat1** [comment]
> Hi @pat1, Thank you so much for your response. I have uncommented and commented the above required stuff. It is still throwing me the error. 

which error?

> And I have gone through the issue #202 for using serial of Arduino UNO. but I'm not getting any response at the end of other client when I'm subscribing to the topic. Even the module is not initiating connection with TCP/IP as well 

how do you know this? what are you monitoring?

> and I am not able to debug it as I have disabled the serial.

This is why I use 644p or 1284P (arduino mega) to devel ; try to use software serial for debug connected to something you can read from .  Or you can try to use software serial for sim800 but for me this is not a good solution.
