### ISSUE TITLE
different version of MQTTClient and example removed

### ISSUE THREAD

**Issue by pat1** [r-map/rmap#223]
la libreria MQTTClient nel branch develop è differente da quella in master.
Quale versione è ?

Inoltre gli esempi risultano modificati ed è stato completamente rimosso sim800Hello che è un significativo test per la implementazione.

**Comment by mbaldinetti** [comment]
la versione è la 1.0.0 presa al seguente link https://www.eclipse.org/downloads/download.php?file=/paho/arduino_1.0.0.zip in ogni caso, non avevo notato l'inclusione del header per il sim800 ed il test sim800hello. ho ripristinato la vecchia versione.
