### ISSUE TITLE
server: rmap-configure do not work with template "stima_report_thpb"

### ISSUE THREAD

**Issue by pat1** [r-map/rmap#254]
@mbaldinetti can you copy the command and the trace with error?

**Comment by mbaldinetti** [comment]
`rmap-configure --addboard --station_slug=stazionediprova --board_slug=stima_report_thpb --user="username" --serialactivate --mqttactivate --mqttuser="username" --mqttpassword="password" --mqttsamplerate=900`

import error:  django_hosts
disable     :  ('django_hosts',)
import error:  cookielaw
disable     :  ('cookielaw',)
import error:  django_extensions
disable     :  ('django_extensions',)
dballe utilities disabled
Traceback (most recent call last):
  File "./rmap-configure", line 133, in <module>
    args.lon=rmap.rmap_core.truncate(args.lon,5)
  File "/home/marco/rmap/python/rmap/rmap_core.py", line 167, in truncate
    return '{0:.{1}f}'.format(f, n)
ValueError: Unknown format code 'f' for object of type 'str'
