### ISSUE TITLE
Lcd display display only time was not set text

### ISSUE THREAD

**Issue by dcast78** [r-map/rmap#26]
Lcd display only show "R-map project" and "time was not set"

**Comment by pat1** [comment]
strange ....
I need the debug messages printed on serial with compile options
Some more lines (for some mqtt publish cycles) will be usefull

**Comment by dcast78** [comment]
Please remind: to resolve timeout un ntp response, we have disabled ntp sync on boot.
Thi is a minor bug with low priority
![img_20150806_182914](https://cloud.githubusercontent.com/assets/3026850/9117445/8001346c-3c6a-11e5-91ca-1159623ec1ed.jpg)




Terminal ready
#54,0,0/105,20,-,-/B12101
#payload:{"v":30377}
#B12101:30377
#{"v":30377}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,20,-,-/B12101
#payload:{"v":30377}
#Started; version: "1.0-470:474M" jsonrpc attuatore sensor ethernet radiorf24 lcd
#Configuration loaded
#sampletime:5
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/
#mqttserver:rmap.cc
#mqttuser:my_user
#mqttpassword:rmy_password
#key:0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15, 
#iv:0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15, 
#ntpserver: pool.ntp.org
#thisnode: 0
# >> CONFIGURE NEW SENSOR: 0
#driver:I2C
#node:1
#type:TMP
#address:72
#mqttpath:254,0,0/105,200,-,-/
#NEW driver: I2CTMP
# >> CONFIGURE NEW SENSOR: 1
#driver:RF24
#node:1
#type:TMP
#address:72
#mqttpath:254,0,0/105,20,-,-/
#NEW driver: RF24TMP
#Try to configure Ethernet using DHCP
#My IP address is 192.168.1.133
#Netmask is 255.255.255.0
#Gateway IP address is 192.168.1.1
#DNS IP address is 192.168.1.1
#time was not set by the sync provider
#mqttid: 00:00:00:00:00:01
#error on mqtt connect
#00:00:08 01 01 1970
#mqtt disconnected
#mqtt reconnected
#mqtt subscribed to: rpc/master
#mqtt reconnected
#Repeats
#ethernet maintain: nothing happened
#The time has never been set
#NULL
#prepare: 0 ok.
#Radio Sending... prepare
#receive: {"jsonrpc":"2.0","result":{"waittime":500},"id":0}
#its a valid response
#waittime: 500
#prepare: 1 ok.
#wait for ms: 500
#getjson: 0
#looping over ajson object: 
#B12101:30633
#{"v":30633}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,200,-,-/B12101
#payload:{"v":30633}
#getjson: 1
#Radio Sending... getjson
#looping over ajson object: 
#B12101:30371
#{"v":30371}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,20,-,-/B12101
#payload:{"v":30371}
#Repeats
#ethernet maintain: nothing happened
#The time has never been set
#NULL
#prepare: 0 ok.
#Radio Sending... prepare
#receive: {"jsonrpc":"2.0","result":{"waittime":500},"id":0}
#its a valid response
#waittime: 500
#prepare: 1 ok.
#wait for ms: 500
#getjson: 0
#looping over ajson object: 
#B12101:30640
#{"v":30640}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,200,-,-/B12101
#payload:{"v":30640}
#getjson: 1
#Radio Sending... getjson
#looping over ajson object: 
#B12101:30371
#{"v":30371}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,20,-,-/B12101
#payload:{"v":30371}
#Repeats
#ethernet maintain: nothing happened
#The time has never been set
#NULL
#prepare: 0 ok.
#Radio Sending... prepare
#receive: {"jsonrpc":"2.0","result":{"waittime":500},"id":0}
#its a valid response
#waittime: 500
#prepare: 1 ok.
#wait for ms: 500
#getjson: 0
#looping over ajson object: 
#B12101:30640
#{"v":30640}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,200,-,-/B12101
#payload:{"v":30640}
#getjson: 1
#Radio Sending... getjson
#looping over ajson object: 
#B12101:30371
#{"v":30371}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,20,-,-/B12101
#payload:{"v":30371}
#Repeats
#ethernet maintain: nothing happened
#The time has never been set
#NULL
#prepare: 0 ok.
#Radio Sending... prepare
#receive: {"jsonrpc":"2.0","result":{"waittime":500},"id":0}
#its a valid response
#waittime: 500
#prepare: 1 ok.
#wait for ms: 500
#getjson: 0
#looping over ajson object: 
#B12101:30646
#{"v":30646}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,200,-,-/B12101
#payload:{"v":30646}
#getjson: 1
#Radio Sending... getjson
#looping over ajson object: 
#B12101:30371
#{"v":30371}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,20,-,-/B12101
#payload:{"v":30371}
#Repeats
#ethernet maintain: nothing happened
#The time has never been set
#NULL
#prepare: 0 ok.
#Radio Sending... prepare
#receive: {"jsonrpc":"2.0","result":{"waittime":500},"id":0}
#its a valid response
#waittime: 500
#prepare: 1 ok.
#wait for ms: 500
#getjson: 0
#looping over ajson object: 
#B12101:30652
#{"v":30652}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,200,-,-/B12101
#payload:{"v":30652}
#getjson: 1
#Radio Sending... getjson
#looping over ajson object: 
#B12101:30371
#{"v":30371}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,20,-,-/B12101
#payload:{"v":30371}
#Repeats
#ethernet maintain: nothing happened
#The time has never been set
#NULL
#prepare: 0 ok.
#Radio Sending... prepare
#receive: {"jsonrpc":"2.0","result":{"waittime":500},"id":0}
#its a valid response
#waittime: 500
#prepare: 1 ok.
#wait for ms: 500
#getjson: 0
#looping over ajson object: 
#B12101:30652
#{"v":30652}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,200,-,-/B12101
#payload:{"v":30652}
#getjson: 1
#Radio Sending... getjson
#looping over ajson object: 
#B12101:30371
#{"v":30371}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,20,-,-/B12101
#payload:{"v":30371}
#Repeats
#ethernet maintain: nothing happened
#The time has never been set
#NULL
#prepare: 0 ok.
#Radio Sending... prepare
#receive: {"jsonrpc":"2.0","result":{"waittime":500},"id":0}
#its a valid response
#waittime: 500
#prepare: 1 ok.
#wait for ms: 500
#getjson: 0
#looping over ajson object: 
#B12101:30658
#{"v":30658}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,200,-,-/B12101
#payload:{"v":30658}
#getjson: 1
#Radio Sending... getjson
#looping over ajson object: 
#B12101:30371
#{"v":30371}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,20,-,-/B12101
#payload:{"v":30371}
#Repeats
#ethernet maintain: nothing happened
#The time has never been set
#NULL
#prepare: 0 ok.
#Radio Sending... prepare
#receive: {"jsonrpc":"2.0","result":{"waittime":500},"id":0}
#its a valid response
#waittime: 500
#prepare: 1 ok.
#wait for ms: 500
#getjson: 0
#looping over ajson object: 
#B12101:30665
#{"v":30665}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,200,-,-/B12101
#payload:{"v":30665}
#getjson: 1
#Radio Sending... getjson
#looping over ajson object: 
#B12101:30371
#{"v":30371}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,20,-,-/B12101
#payload:{"v":30371}
#Repeats
#ethernet maintain: nothing happened
#The time has never been set
#NULL
#prepare: 0 ok.
#Radio Sending... prepare
#receive: {"jsonrpc":"2.0","result":{"waittime":500},"id":0}
#its a valid response
#waittime: 500
#prepare: 1 ok.
#wait for ms: 500
#getjson: 0
#looping over ajson object: 
#B12101:30665
#{"v":30665}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,200,-,-/B12101
#payload:{"v":30665}
#getjson: 1
#Radio Sending... getjson
#looping over ajson object: 
#B12101:30371
#{"v":30371}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,20,-,-/B12101
#payload:{"v":30371}
#Repeats
#ethernet maintain: nothing happened
#The time has never been set
#NULL
#prepare: 0 ok.
#Radio Sending... prepare
#receive: {"jsonrpc":"2.0","result":{"waittime":500},"id":0}
#its a valid response
#waittime: 500
#prepare: 1 ok.
#wait for ms: 500
#getjson: 0
#looping over ajson object: 
#B12101:30671
#{"v":30671}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,200,-,-/B12101
#payload:{"v":30671}
#getjson: 1
#Radio Sending... getjson
#looping over ajson object: 
#B12101:30371
#{"v":30371}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,20,-,-/B12101
#payload:{"v":30371}
#Repeats
#ethernet maintain: nothing happened
#The time has never been set
#NULL
#prepare: 0 ok.
#Radio Sending... prepare
#receive: {"jsonrpc":"2.0","result":{"waittime":500},"id":0}
#its a valid response
#waittime: 500
#prepare: 1 ok.
#wait for ms: 500
#getjson: 0
#looping over ajson object: 
#B12101:30671
#{"v":30671}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,200,-,-/B12101
#payload:{"v":30671}
#getjson: 1
#Radio Sending... getjson
#looping over ajson object: 
#B12101:30371
#{"v":30371}
#mqttrootpath:rmap/my_user/1137625,4449216/rmap/254,0,0/105,20,-,-/B12101
#payload:{"v":30371}

**Comment by pat1** [comment]
need check with the last firmware
