### ISSUE TITLE
No need to wait after Wire.requestFrom() and it should not be followed by Wire.endTransmission().

### ISSUE THREAD

**Issue by Koepel** [r-map/rmap#275]
In the file "rmap/arduino/sketchbook/rmap/rmap/rmap.ino", there is a timeout after Wire.endTransmission() and a Wire.endTransmission() at the end of the function. Those can be removed.
Explanation: [Common-mistakes](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes), number 1 and 2.

Without timeout, it could be for example this:
```
  Wire.requestFrom(I2C_GPS_ADDRESS, 8);
  
  if (Wire.available() != 8){
    IF_SDEBUG(DBGSERIAL.println(F("#error getting I2CGPS LON LAT"))) ;
    *lat=0;
    *lon=0;
    return;
  }
  
  *lat = Wire.read();
  *lat = *lat | ((int32_t)Wire.read())<<8 ;
  ...
```

**Comment by Koepel** [comment]
There are a few more in the file "rmap/arduino/sketchbook/libraries/SensorDriverb/SensorDriverb.cpp".

In the function "SensorDriverBmp085::read8()" and "SensorDriverBmp085::read16()", the `Wire.beginTransmission()` before and the `Wire.endTransmission()` after the `Wire.requestFrom()` may be removed.
There is no need to be compatible with `Wire.send()` and `Wire.receive()` anymore. No one uses an Arduino IDE older than version 1.0.

**Comment by Koepel** [comment]
Could you check the new code. I think the function "SensorDriverBmp085::read8()" in "rmap/arduino/sketchbook/libraries/SensorDriverb/SensorDriverb.cpp" still has a `Wire.endTransmission()` after the `Wire.requestFrom()`.

**Comment by pat1** [comment]
thanks, I hope now is correct...
