### ISSUE TITLE
Rmap for RainBO project: graphite error during the registration of a new user

### ISSUE THREAD

**Issue by stefipase** [r-map/rmap#278]
The following error occurs when I try to register a new user on the Rmap4Rainbo application (https://partecipa.rainbolife.eu/registrazione/register/):
"Graphite encountered an unexpected error while handling your request. Please contact your site administrator if the problem persists."
thank you.
Stefania

**Comment by pat1** [comment]
Ho dovuto cambiare il mailserver usato per il processo di registrazione.

**Comment by stefipase** [comment]
grazie molte Paolo, ora funziona!
Stefania
