### ISSUE TITLE
server: borinud do not manage dballe attributes

### ISSUE THREAD

**Issue by pat1** [r-map/rmap#319]
related to https://github.com/ARPA-SIMC/cosudo/issues/28

**Comment by pat1** [comment]
@edigiacomo 
https://github.com/r-map/rmap/commit/b36fd748dc3c01eb290db2ad2835bf5699f9467c
rimane che il json viene composto variabile per variabile una alla volta mentre le specifiche RMAP prevedono che vars sia un array

**Comment by edigiacomo** [comment]
Ottimo! Comunque, anche se c'è un JSON per variabile non credo che sia un problema dal punto di vista dell'RFC: lo schema del JSON è il medesimo - semplicemente è meno ottimizzato perché ripete un intero JavaScript Object per ogni var invece che metterle dentro ad un solo.

**Comment by pat1** [comment]
closed by bb48eddb
