### ISSUE TITLE
Missing negative temperature data

### ISSUE THREAD

**Issue by mbaldinetti** [r-map/rmap#329]
Missing negative temperature data

**Comment by pat1** [comment]
avevo richiesto una pull request ...
riapro per fare una revert , tag pull request etc

**Comment by pat1** [comment]
f01cbab siamo in due in ARPAE a non comprendere il senso della patch
le due variabili sono float e fare la differenza dei loro abs o l'abs della differenza dovrebbe essere abbastanza indifferente salvo forse situazioni di underflow e overflow
@mbaldinetti sapresti spiegarci il senso della patch ?

**Comment by pat1** [comment]
anzi l'ordine di esecuzione degli abs non è indifferente nel caso di temperature misurata e di conferma con segno differente, ma risulterebbe corretta la formula prima della patch e non dopo

**Comment by mbaldinetti** [comment]
dopo alcune verifiche confermo che la patch è errata.
Il codice era già correttamente funzionante così senza bug delle temperature negative.
