### ISSUE TITLE
server: add a last seen timestamp for stations web ui

### ISSUE THREAD

**Issue by eineki** [r-map/rmap#347]
In the user personal page, there is a summary of stations owned.
Adding a field with the timestamp of the last data packet received from a stations, would allow the owner to quick check if him/her stations are still functional

**Comment by pat1** [comment]
tutta la parte di protocollo RMAP https://doc.rmap.cc/rmap_rfc/rfc.html#dati-e-metadati-su-mqtt alla sezione "Stato della connessione" è dedicato a questa funzione.
Manca completamente la gestione software lato server.

**Comment by pat1** [comment]
related to #52

**Comment by pat1** [comment]
duplicate of #52
