### ISSUE TITLE
firmware: sensordriver leaf driver  check type

### ISSUE THREAD

**Issue by pat1** [r-map/rmap#366]
at:
https://github.com/r-map/rmap/blob/1ecdf3e08ed5aca000b6beb3276c23a9a8b89c1c/platformio/libraries/SensorDriver/SensorDriver.cpp#L3471
https://github.com/r-map/rmap/blob/1ecdf3e08ed5aca000b6beb3276c23a9a8b89c1c/platformio/libraries/SensorDriver/SensorDriver.cpp#L3523
https://github.com/r-map/rmap/blob/1ecdf3e08ed5aca000b6beb3276c23a9a8b89c1c/platformio/libraries/SensorDriver/SensorDriver.cpp#L3554
https://github.com/r-map/rmap/blob/1ecdf3e08ed5aca000b6beb3276c23a9a8b89c1c/platformio/libraries/SensorDriver/SensorDriver.cpp#L3615
https://github.com/r-map/rmap/blob/1ecdf3e08ed5aca000b6beb3276c23a9a8b89c1c/platformio/libraries/SensorDriver/SensorDriver.cpp#L3651

there are tests that I do not understand

**Comment by mbaldinetti** [comment]
it is for general use in anticipation of the implementation of new sensors within the same module and for uniformity to the others
