### ISSUE TITLE
firmware: IST sensor declare not compatible min I2C clock frequency

### ISSUE THREAD

**Issue by pat1** [r-map/rmap#369]
https://www.ist-ag.com/sites/default/files/ahhytm_e.pdf
pg 15 declare:

 SCL clock frequencyfSCL   MIN 100      MAX 400kHz

and we use 30Khz clock ...

**Comment by mbaldinetti** [comment]
Those are the standard speeds at which the I2C bus operates.
This does not mean that these speeds cannot be different and in particular lower, as reported by https://www.i2c-bus.org/speed

"...The speed grades (standard mode: 100 kbit/s, full speed: 400 kbit/s, fast mode: 1 mbit/s, high speed: 3,2 Mbit/s) are maximum ratings. Compliant hardware guaranties that it can handle transmission speed up to the maximum clock rate specified by the mode.

This does not imply that a transmission may not take place at any lower speed or even at a somewhat variable bit rate..."
