### ISSUE TITLE
firmware: IST sensor conversion time 

### ISSUE THREAD

**Issue by pat1** [r-map/rmap#370]
At https://www.ist-ag.com/sites/default/files/ahhytm_e.pdf
pg 15

 The conversion time is between 60 and 100 milliseconds.

but in the library:

https://github.com/r-map/rmap/blob/69cd23d50b1c73bd7b6c88eb3f5ffa9af6ff52db/platformio/libraries/HYT2X1/hyt2x1.h#L63
```
/*!
\def HYT2X1_CONVERSION_TIME_MS
\brief Conversion time in milliseconds.
*/
#define HYT2X1_CONVERSION_TIME_MS     (200)
```

**Comment by mbaldinetti** [comment]
it is a safety margin to say that in 200ms you are sure that the conversion is finished
