### ISSUE TITLE
how we can power supply miroduino PoE ?

### ISSUE THREAD

**Issue by pat1** [r-map/rmap#40]
Ho posto questa questione sul forum di microduino:
https://www.microduino.cc/forum/topic/72/power-over-ethernet-with-microduino-enc28j60

considerando questo schema elettrico:
[Microduino-RJ45.pdf](https://github.com/r-map/rmap/files/6915/Microduino-RJ45.pdf)
avete suggerimenti ?

Viste le caratteristiche del LM2674
http://www.farnell.com/datasheets/10234.pdf
parrebbe che 24 V siano la tensione giusta, ma da appllicare dove e
come ?

**Comment by pat1** [comment]
I suppose that the module require
10/100 mode B,DC on spares with 24V
so the http://dlnmh9ip6v2uc.cloudfront.net/datasheets/Cables/Ethernet/poedatadsheet.pdf cable have to work without problems.

**Comment by pat1** [comment]
e funziona.

**Comment by dcast78** [comment]
ottimo!
Il 12/ott/2015 03:52 PM, "Paolo Patruno" <notifications@github.com> ha
scritto:
