### ISSUE TITLE
stimav4: master board do not compile

### ISSUE THREAD

**Issue by pat1** [r-map/rmap#436]
```
[pat1@localhost master]$ pio run
Processing stimav4_master (board: stimav4_master; platform: ststm32; framework: arduino)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Error: Unknown board ID 'stimav4_master'
```

**Comment by digitecomg** [comment]
All'interno della cartella stima4v c'è una cartella boards
i files json vanno caricati nelle boards arduino:
stimav4_master.json e stimav4_slave.json in .platformio\platforms\ststm32\boards

Le directory (interessano poi solo i files variant_stima*.*)
 - L452R(C-E)(I-T-Y)_L462RE(I-T-Y)
 - L496V(E-G)T_L4A6VGT
Nelle directory dei variant in .platformio\packages\framework-arduinoststm32\variants\STM32L4xx

Successivamente seguire una nota all'interno del file note nella cartella user_custom di master

**Comment by pat1** [comment]
ported configuration to platformio.ini
