### ISSUE TITLE
v7d_transform do not create report any more

### ISSUE THREAD

**Issue by pat1** [r-map/rmap#79]
the command:
v7d_transform --input-format=dba --output-format=BUFR --network-list=rmap --start-date "2016-01-17 10:13:40" --end-date "2016-01-17 23:15:00" --comp-start "2016-01-17 10:13:40" --comp-step "0000000000 00:01:00.000" --comp-frac-valid .002 --comp-stat-proc=254:0 --set-network generic  rmap/rmap@rmap -

have no output

**Comment by dcesari** [comment]
Can you attach an input example?
Which is the frequency of input data?
longest=comp-step/(comp-frac-valid*999  +1)=~0.33*comp-step=~20''

**Comment by pat1** [comment]
frequency of input data should be 5 sec.
[rmap.zip](https://github.com/r-map/rmap/files/94038/rmap.zip)

**Comment by pat1** [comment]
il problema è di dballe che nelle api fortran non scrive più in stdout quando il nomefile è "".

**Comment by pat1** [comment]
il problema era in libsim; risolto
